name: 安全极简编译（解决清理失败问题）
on:
  workflow_dispatch:
    inputs:
      device:
        default: "rubens"
        type: string

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: 安全清理磁盘（释放50GB+空间，不破坏系统）
        run: |
          set -euo pipefail
          
          # 1. 安全删除大型已知目录（不影响系统核心）
          SAFE_DELETE=(
            "/var/lib/docker"           # Docker镜像（10-20GB）
            "/usr/local/lib/android"    # Android SDK残留（5+GB）
            "/usr/share/dotnet"         # .NET框架（5+GB）
            "/opt/ghc"                  # Haskell编译器（3+GB）
            "/usr/local/share/boost"    # Boost库（2+GB）
            "/var/cache/apt/archives"   # APT缓存（2+GB）
            "/var/lib/apt/lists"        # APT列表（1+GB）
            "/var/log"                  # 系统日志（1+GB）
            "/tmp/*"                    # 临时文件
            "$HOME/.cache"              # 用户缓存
            "$HOME/.local"              # 用户本地文件
          )
          
          for dir in "${SAFE_DELETE[@]}"; do
            if [ -e "$dir" ]; then
              echo "删除: $dir"
              sudo rm -rf "$dir" || echo "警告：$dir 删除失败，跳过"
            fi
          done
          
          # 2. 清理APT冗余包
          sudo apt clean
          sudo apt autoremove -y --purge
          
          # 3. 验证剩余空间（确保/mnt有>50GB）
          echo -e "\n=== 清理后磁盘空间 ==="
          df -h /mnt

      - name: 安装最小编译工具链
        run: |
          sudo apt update
          sudo apt install -y \
            git gcc-aarch64-linux-gnu make bc bison flex libssl-dev dtc \
            cpio openssl liblz4-tool zstd

      # 后续步骤与之前相同（拉取源码、应用补丁、编译）
      - name: 拉取内核源码
        run: |
          mkdir -p /mnt/build/kernel
          cd /mnt/build/kernel
          git clone --depth=1 https://github.com/LineageOS/android_kernel_xiaomi_sm8450.git -b lineage-20 .

      - name: 拉取设备树和厂商库
        run: |
          mkdir -p /mnt/build/device/rubens
          cd /mnt/build/device/rubens
          git clone --depth=1 https://github.com/LineageOS/android_device_xiaomi_rubens.git -b lineage-20 .

          mkdir -p /mnt/build/vendor/rubens
          cd /mnt/build/vendor/rubens
          git clone --depth=1 https://github.com/LineageOS/android_vendor_xiaomi_rubens.git -b lineage-20 .

          mkdir -p /mnt/build/vendor/sm8450-common
          cd /mnt/build/vendor/sm8450-common
          git clone --depth=1 https://github.com/LineageOS/android_vendor_xiaomi_sm8450-common.git -b lineage-20 .

      - name: 应用硬件修复补丁
        run: |
          chmod +x $GITHUB_WORKSPACE/scripts/apply-all-patches.sh
          $GITHUB_WORKSPACE/scripts/apply-all-patches.sh

      - name: 编译内核和dtb/dtbo
        run: |
          cd /mnt/build/kernel
          make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- vendor/rubens_defconfig
          make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- -j2 dtbs dtbo.img
          mkdir -p /mnt/build/out
          cp arch/arm64/boot/dtb /mnt/build/out/dtb.img
          cp arch/arm64/boot/dtbo.img /mnt/build/out/

      - name: 手动打包vendor镜像
        run: |
          mkdir -p /mnt/build/vendor_img/{vendor,system}
          cp -r /mnt/build/vendor/rubens/* /mnt/build/vendor_img/vendor/
          cp -r /mnt/build/vendor/sm8450-common/* /mnt/build/vendor_img/vendor/
          VENDOR_SIZE=$(du -sh /mnt/build/vendor_img | awk '{print $1}' | sed 's/G//')
          VENDOR_SIZE=$(( ${VENDOR_SIZE%.*} + 2 ))
          dd if=/dev/zero of=/mnt/build/out/vendor.img bs=1G count=$VENDOR_SIZE
          mkfs.ext4 -F /mnt/build/out/vendor.img
          sudo mount /mnt/build/out/vendor.img /mnt/build/vendor_img/system
          sudo cp -r /mnt/build/vendor_img/vendor/* /mnt/build/vendor_img/system/
          sudo umount /mnt/build/vendor_img/system

      - name: 编译vendor_dlkm
        run: |
          mkdir -p /mnt/build/out/vendor_dlkm
          cp -r /mnt/build/device/rubens/dlkm/* /mnt/build/out/vendor_dlkm/
          find /mnt/build/out/vendor_dlkm -print0 | cpio -0 -H newc -o | gzip > /mnt/build/out/vendor_dlkm.img

      - name: 上传产物
        uses: actions/upload-artifact@v4
        with:
          name: safe-artifacts-${{ github.event.inputs.device }}
          path: /mnt/build/out/
          retention-days: 14
