name: Build Redmi SM8450 Components

on:
  workflow_dispatch:
    inputs:
      device:
        default: 'rubens'
        type: string
      build_type:
        default: 'userdebug'
        type: choice
        options: [user, userdebug, eng]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: 强制拉取最新代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 清理磁盘空间（关键步骤）
        run: |
          # 查看初始磁盘使用情况
          df -h

          # 删除不必要的预装软件和文件
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf /var/cache/apt/archives/*
          sudo apt clean
          sudo apt autoremove -y

          # 移动Android源码到更大的临时分区（/mnt空间更大）
          sudo mkdir -p /mnt/android
          sudo chown -R $USER:$USER /mnt/android

          # 再次查看清理后的磁盘使用情况
          df -h

      - name: 终极调试 - 显示文件路径
        run: |
          find . -name "redmi-sm8450.xml"
          ls -la ./local_manifests/ || echo "local_manifests目录不存在"

      - name: 安装依赖
        run: |
          sudo apt update
          sudo apt install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git git-lfs gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev libelf-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev openjdk-17-jdk
          sudo apt remove -y repo
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/repo && chmod a+x ~/repo && sudo mv ~/repo /usr/local/bin/

      - name: 同步源码（使用更大的临时分区）
        run: |
          # 使用/mnt分区存储源码（空间更大）
          mkdir -p /mnt/android/redmi && cd /mnt/android/redmi
          repo init -u https://github.com/LineageOS/android.git -b lineage-20.0 --depth=1
          mkdir -p .repo/local_manifests

          # 复制清单文件
          MANIFEST_PATH=$(find $GITHUB_WORKSPACE -name "redmi-sm8450.xml" | head -n 1)
          if [ -z "$MANIFEST_PATH" ]; then
            echo "❌ 找不到redmi-sm8450.xml"
            exit 1
          else
            cp "$MANIFEST_PATH" .repo/local_manifests/
          fi

          # 同步源码（限制并行数减少内存占用）
          repo sync -c --no-clone-bundle --no-tags -j4

      - name: 应用补丁
        run: |
          cd /mnt/android/redmi
          [ -f "$GITHUB_WORKSPACE/scripts/apply-patches.sh" ] && $GITHUB_WORKSPACE/scripts/apply-patches.sh || echo "跳过补丁"

      - name: 编译组件（优化空间使用）
        run: |
          cd /mnt/android/redmi
          # 限制ccache大小，避免占用过多空间
          export USE_CCACHE=1
          export CCACHE_EXEC=$(which ccache)
          ccache -M 20G  # 减小缓存大小，默认50G可能太大

          # 开始编译（减少并行数，避免IO压力过大）
          $GITHUB_WORKSPACE/scripts/build.sh ${{ github.event.inputs.device }} ${{ github.event.inputs.build_type }}

      - name: 收集编译产物
        run: |
          mkdir -p $GITHUB_WORKSPACE/out
          cp /mnt/android/redmi/out/target/product/${{ github.event.inputs.device }}/*.img $GITHUB_WORKSPACE/out/ || echo "部分镜像未找到"
          df -h  # 查看最终磁盘使用情况

      - name: 上传编译产物
        uses: actions/upload-artifact@v4
        with:
          name: redmi-artifacts-${{ github.event.inputs.device }}
          path: out/
          retention-days: 7
