name: Build Redmi SM8450 Components

on:
  workflow_dispatch:
    inputs:
      device:
        description: '选择设备型号'
        required: true
        default: 'rubens'  # Redmi K50 Ultra的代号
        type: choice
        options:
          - rubens
          # 可添加其他SM8450设备代号

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build for ${{ github.event.inputs.device }}

    steps:
      - name: 检查系统环境
        run: |
          echo "当前系统: $(lsb_release -d | cut -f2)"
          echo "CPU核心数: $(nproc --all)"
          echo "可用内存: $(free -h | awk '/^Mem:/ {print $2}')"

      - name: 安装依赖
        run: |
          sudo apt update
          sudo apt install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git git-lfs gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev libelf-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev openjdk-11-jdk

      - name: 配置CCache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ github.event.inputs.device }}-ccache

      - name: 准备源码目录
        run: |
          mkdir -p ~/android/redmi
          cd ~/android/redmi

      - name: 同步源码
        run: |
          cd ~/android/redmi
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # 初始化repo
          curl https://storage.googleapis.com/git-repo-downloads/repo > repo
          chmod a+x repo
          sudo mv repo /usr/local/bin/
          
          # 同步基础源码（以LineageOS为例，可根据需要修改）
          repo init -u https://github.com/LineageOS/android.git -b lineage-20.0 --depth=1
          
          # 应用设备特定清单
          mkdir -p .repo/local_manifests
          cp $GITHUB_WORKSPACE/local_manifests/redmi-sm8450.xml .repo/local_manifests/
          
          # 同步源码
          repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all)

      - name: 应用补丁
        run: |
          cd ~/android/redmi
          # 应用设备树补丁（用于解锁电池容量）
          if [ -d "$GITHUB_WORKSPACE/patches/dtb-patch" ]; then
            git apply $GITHUB_WORKSPACE/patches/dtb-patch/*.patch
          fi

      - name: 执行编译
        run: |
          cd ~/android/redmi
          export CCACHE_DIR=$GITHUB_WORKSPACE/.ccache
          export CCACHE_EXEC=$(which ccache)
          ccache -M 50G
          
          # 运行编译脚本
          $GITHUB_WORKSPACE/scripts/build.sh ${{ github.event.inputs.device }}

      - name: 收集编译产物
        run: |
          mkdir -p $GITHUB_WORKSPACE/output
          cp ~/android/redmi/out/target/product/${{ github.event.inputs.device }}/vendor.img $GITHUB_WORKSPACE/output/
          cp ~/android/redmi/out/target/product/${{ github.event.inputs.device }}/vendor_dlkm.img $GITHUB_WORKSPACE/output/
          cp ~/android/redmi/out/target/product/${{ github.event.inputs.device }}/dtb.img $GITHUB_WORKSPACE/output/
          cp ~/android/redmi/out/target/product/${{ github.event.inputs.device }}/dtbo.img $GITHUB_WORKSPACE/output/
          ls -lh $GITHUB_WORKSPACE/output/

      - name: 上传产物
        uses: actions/upload-artifact@v3
        with:
          name: redmi-sm8450-builds-${{ github.event.inputs.device }}
          path: output/
          retention-days: 7
