name: 安全极简编译（修复/mnt目录权限）
on:
  workflow_dispatch:
    inputs:
      device:
        default: "rubens"
        type: string

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: 安全清理磁盘空间
        run: |
          set -euo pipefail
          
          # 备份APT日志目录
          if [ -d "/var/log/apt" ]; then
            sudo mv /var/log/apt /tmp/apt-log-backup
          fi
          
          # 删除大型无用目录
          sudo rm -rf /var/lib/docker /usr/local/lib/android /usr/share/dotnet /opt/ghc /usr/local/share/boost
          sudo rm -rf /var/cache/apt/archives/* /var/lib/apt/lists/* /var/log/* /tmp/* ~/.cache ~/.local
          
          # 恢复/新建APT日志目录
          if [ -d "/tmp/apt-log-backup" ]; then
            sudo mv /tmp/apt-log-backup /var/log/apt
          else
            sudo mkdir -p /var/log/apt
          fi
          sudo chown -R root:root /var/log/apt
          sudo chmod 0755 /var/log/apt
          
          # 清理APT冗余
          sudo apt clean
          sudo apt autoremove -y --purge || echo "部分包删除失败，继续执行"
          
          # 查看空间
          df -h /mnt

      - name: 安装最小编译依赖
        run: |
          sudo apt update
          sudo apt install -y \
            git gcc-aarch64-linux-gnu make bc bison flex libssl-dev \
            device-tree-compiler cpio openssl liblz4-tool zstd

      # 新增步骤：创建/mnt/build目录并授权（解决权限问题）
      - name: 初始化编译目录（授权权限）
        run: |
          # 用sudo创建/mnt/build目录（需要root权限）
          sudo mkdir -p /mnt/build
          # 将目录所有权赋予当前用户（避免后续操作权限不足）
          sudo chown -R $USER:$USER /mnt/build
          # 验证权限
          ls -ld /mnt/build  # 应显示当前用户为所有者

      - name: 拉取内核源码
        run: |
          # 现在有权限创建子目录了
          mkdir -p /mnt/build/kernel
          cd /mnt/build/kernel
          git clone --depth=1 https://github.com/LineageOS/android_kernel_xiaomi_sm8450.git -b lineage-20 .

      - name: 拉取设备树与厂商库
        run: |
          # 设备树
          mkdir -p /mnt/build/device/rubens
          cd /mnt/build/device/rubens
          git clone --depth=1 https://github.com/LineageOS/android_device_xiaomi_rubens.git -b lineage-20 .
          
          # 设备专属厂商库
          mkdir -p /mnt/build/vendor/rubens
          cd /mnt/build/vendor/rubens
          git clone --depth=1 https://github.com/LineageOS/android_vendor_xiaomi_rubens.git -b lineage-20 .
          
          # 通用厂商库
          mkdir -p /mnt/build/vendor/sm8450-common
          cd /mnt/build/vendor/sm8450-common
          git clone --depth=1 https://github.com/LineageOS/android_vendor_xiaomi_sm8450-common.git -b lineage-20 .

      - name: 应用补丁（解锁电池/显示/分区）
        run: |
          chmod +x $GITHUB_WORKSPACE/scripts/apply-all-patches.sh
          $GITHUB_WORKSPACE/scripts/apply-all-patches.sh

      - name: 编译内核和设备树
        run: |
          cd /mnt/build/kernel
          make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- vendor/rubens_defconfig
          make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- -j2 dtbs dtbo.img
          mkdir -p /mnt/build/out
          cp arch/arm64/boot/dtb /mnt/build/out/dtb.img
          cp arch/arm64/boot/dtbo.img /mnt/build/out/

      - name: 打包vendor.img
        run: |
          mkdir -p /mnt/build/vendor_img/{vendor,system}
          cp -r /mnt/build/vendor/rubens/* /mnt/build/vendor_img/vendor/
          cp -r /mnt/build/vendor/sm8450-common/* /mnt/build/vendor_img/vendor/
          VENDOR_SIZE=$(du -sh /mnt/build/vendor_img | awk '{print $1}' | sed 's/G//')
          VENDOR_SIZE=$(( ${VENDOR_SIZE%.*} + 2 ))
          dd if=/dev/zero of=/mnt/build/out/vendor.img bs=1G count=$VENDOR_SIZE
          mkfs.ext4 -F /mnt/build/out/vendor.img
          sudo mount /mnt/build/out/vendor.img /mnt/build/vendor_img/system
          sudo cp -r /mnt/build/vendor_img/vendor/* /mnt/build/vendor_img/system/
          sudo umount /mnt/build/vendor_img/system

      - name: 打包vendor_dlkm.img
        run: |
          mkdir -p /mnt/build/out/vendor_dlkm
          cp -r /mnt/build/device/rubens/dlkm/* /mnt/build/out/vendor_dlkm/
          find /mnt/build/out/vendor_dlkm -print0 | cpio -0 -H newc -o | gzip > /mnt/build/out/vendor_dlkm.img

      - name: 上传编译产物
        uses: actions/upload-artifact@v4
        with:
          name: final-artifacts-${{ github.event.inputs.device }}
          path: /mnt/build/out/
          retention-days: 14
    
